# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20170122_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action',
        ),
    ]
