# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20170118_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, to='videos.Video'),
        ),
    ]
