# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20170119_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='share_message',
            field=models.TextField(default='\nCheck me\n'),
        ),
    ]
