# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20170127_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMerchatnId',
            new_name='UserMerchantId',
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 27, 18, 0, 29, 259768, tzinfo=utc), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 27, 18, 0, 29, 259547, tzinfo=utc), verbose_name='Start date'),
        ),
    ]
