# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 04:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateTimeField(default=datetime.datetime(2017, 1, 27, 4, 27, 6, 77258, tzinfo=utc))),
                ('date_start', models.DateTimeField(default=datetime.datetime(2017, 1, 27, 4, 27, 6, 77485, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
