# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20170127_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2017, 1, 27, 3, 7, 11, 356788, tzinfo=utc)),
        ),
    ]
