# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 03:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20170127_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2017, 1, 27, 3, 8, 12, 811304, tzinfo=utc)),
        ),
    ]
