# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 05:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_auto_20170127_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 27, 5, 2, 9, 467789, tzinfo=utc)),
        ),
    ]
